### ISSUE TITLE
Rails 5.2 release

### ISSUE THREAD

**Issue by mattruzicka** [maximeg/activecleaner#5]
I see this commit was added to test against Rails 5.2 9dd1e740236c6c2bbb0b54a5e4130816bb44a597 but no release was made. Is this gem ready for 5.2? Would it be possible to create a new release?

**Comment by maximeg** [comment]
Hey,

Thanks for pointing out. I've also added Rails 6.0 in the matrix.

I just released version`0.3.3` with it.
